theme = "tokyonight"
client_id = "8c04fcb8db894a398792c86721609228"
app_refresh_duration_in_ms = 5
playback_refresh_duration_in_ms = 0
cover_image_refresh_duration_in_ms = 2000
track_table_item_max_len = 32
enable_media_control = true
default_device = "spotify-player"

[device]
name = "spotify-player"
device_type = "computer"
volume = 100
bitrate = 320
audio_cache = true
