[[themes]]
name = "tokyonight"
[themes.palette]
background = "#1a1b26"
foreground = "#c0caf5"
black = "#15161e"
blue = "#7aa2f7"
cyan = "#7dcfff"
green = "#9ece6a"
magenta = "#bb9af7"
red = "#f7768e"
white = "#a9b1d6"
yellow = "#e0af68"
bright_black = "#414868"
bright_blue = "#7aa2f7"
bright_cyan = "#7dcfff"
bright_green = "#9ece6a"
bright_magenta = "#bb9af7"
bright_red = "#f7768e"
bright_white = "#c0caf5"
bright_yellow = "#e0af68"
selection_background = "#33467c"
selection_foreground =  "#c0caf5"
[themes.component_style]
block_title = { fg = "Magenta"  }
playback_track = { fg = "Cyan", modifiers = ["Bold"] }
playback_album = { fg = "Yellow" }
playback_metadata = { fg = "BrightBlack" }
playback_progress_bar = { bg = "SelectionBackground", fg = "Green" }
current_playing = { fg = "Green", modifiers = ["Bold"] }
page_desc = { fg = "Cyan", modifiers = ["Bold"] }
table_header = { fg = "Blue" }
